# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8111a83c2565f96d27c1a90e9f4886b61605afd2c5bf7dfc68615b372d3841b064a750a554cf3cb7dcb05cf3d9db0d7ec0b5d0baf076118f99011513ba21ce59

test:
  secret_key_base: ae8cb4d1af88551a25a977640272f96cd8a57f83c2c88e2ba94a31bea19841cfe337ce0ae9688ff4274a2943e03218411695627cfcb24425693658d4f2bb7869

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
